version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/hacker-news
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: hacker-news-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: hacker-news-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      - run: npm run lint
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build -- --prod
workflows:
    build-and-test:
      jobs:
        - build-and-test
